/**
 * Page Object extraction (F4) — lift flows shared across saved specs into
 * `pages/<Name>.ts` + a `fixtures.ts` entry point, then FOLD the specs that use
 * them (they consume `await xPage.x()` from `./fixtures` instead of repeating
 * the steps). Fully deterministic — no LLM.
 *
 * MCP-first trigger: after `test_app` crystallizes the suite, the agent calls
 * `detect_shared_flows`, ASKS the user, and on yes calls this. LOGIN prefixes
 * are EXCLUDED — auth-fixture already lifts login into auth.setup.ts, and
 * folding it here would double it. So this only extracts NON-login shared
 * entry flows (the case that scales on large suites).
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { SkillStep } from './specStep.js';
import { detectSharedFlows, type SharedFlow } from './detectSharedFlows.js';
import { generatePageObject } from './generatePageObject.js';
import { writePageObjectManifest, type PageObjectEntry } from './pageObjectManifest.js';
import { reRenderSpec } from './writeSpec.js';

export interface ExtractedPage {
  className: string;
  methodName: string;
  fileName: string;
  path: string;
  /** Slugs of the specs that share this flow. */
  specs: string[];
}

export interface ExtractResult {
  pages: ExtractedPage[];
  fixturesPath: string | null;
  /** Slugs re-rendered to consume the new Page Objects. */
  folded: string[];
}

/** A shared prefix is a LOGIN (auth-fixture's job, not a POM) when it types a
 *  credential — the sidecar's fill value is a `process.env.<X>` ref. */
function isLoginPrefix(steps: SkillStep[]): boolean {
  return steps.some((s) => {
    if (s.kind !== 'step') return false;
    const tool = (s.tool ?? '').replace(/^mcp__[a-z0-9_-]+?__/, '');
    const input = (s.input ?? {}) as Record<string, unknown>;
    const v = tool === 'browser_type' ? input.text : tool === 'fill_control' ? input.value : null;
    return typeof v === 'string' && /process\.env\./.test(v);
  });
}

/** Detect shared flows worth extracting — NON-login prefixes shared by >= minSpecs
 *  specs. Read-only: the agent uses this to decide what to ASK the user about. */
export async function detectExtractableFlows(devRoot: string, minSpecs = 2): Promise<SharedFlow[]> {
  const flows = await detectSharedFlows(devRoot, { minSpecs });
  return flows.filter((f) => !isLoginPrefix(f.prefixSteps));
}

export async function extractPageObjects(
  devRoot: string,
  opts: { minSpecs?: number } = {},
): Promise<ExtractResult> {
  const flows = await detectExtractableFlows(devRoot, opts.minSpecs ?? 2);
  if (flows.length === 0) return { pages: [], fixturesPath: null, folded: [] };

  const testsDir = join(devRoot, '__vibe_tests__');
  const pagesDir = join(testsDir, 'pages');
  await mkdir(pagesDir, { recursive: true });

  const pages: ExtractedPage[] = [];
  const entries: PageObjectEntry[] = [];
  const usedNames = new Set<string>();
  const affected = new Set<string>();
  for (const flow of flows) {
    const probe = generatePageObject(flow.prefixSteps);
    const className = uniqueName(probe.className, usedNames);
    const po = className === probe.className ? probe : generatePageObject(flow.prefixSteps, { className });
    const path = join(pagesDir, po.fileName);
    await writeFile(path, po.source, 'utf-8');
    pages.push({ className: po.className, methodName: po.methodName, fileName: po.fileName, path, specs: flow.specs });
    entries.push({
      className: po.className,
      methodName: po.methodName,
      fixtureName: fixtureName(po.className),
      fileName: po.fileName,
      signatures: flow.signatures,
      specs: flow.specs,
    });
    flow.specs.forEach((s) => affected.add(s));
  }

  const fixturesPath = join(testsDir, 'fixtures.ts');
  await writeFile(fixturesPath, renderFixtures(pages), 'utf-8');
  // The manifest lets writeSpec's matchPageObject fold a matching prefix.
  await writePageObjectManifest(devRoot, entries);

  // Fold NOW: faithfully re-render each affected spec so it consumes the Page
  // Object (via reRenderSpec, which re-applies auth-fixture/base-url from the
  // sidecar — never regressing them). Non-login prefixes → no auth conflict.
  const folded: string[] = [];
  for (const slug of affected) {
    try {
      if (await reRenderSpec(devRoot, slug)) folded.push(slug);
    } catch {
      /* a fold is best-effort — the page/fixture still exist for future specs */
    }
  }
  return { pages, fixturesPath, folded };
}

function renderFixtures(pages: ExtractedPage[]): string {
  const lines: string[] = [
    `import { test as base } from '@playwright/test';`,
    ...pages.map((p) => `import { ${p.className} } from './pages/${p.className}';`),
    ``,
    `/**`,
    ` * Generated by Hover — Page Object fixtures lifted from flows shared across`,
    ` * specs. In an e2e spec: \`import { test, expect } from '../fixtures';\` then consume`,
    ` * e.g. \`async ({ page, ${pages[0] ? fixtureName(pages[0].className) : 'somePage'} }) => …\`.`,
    ` */`,
    `export const test = base.extend<{ ${pages.map((p) => `${fixtureName(p.className)}: ${p.className}`).join('; ')} }>({`,
    ...pages.flatMap((p) => [
      `  ${fixtureName(p.className)}: async ({ page }, use) => {`,
      `    await use(new ${p.className}(page));`,
      `  },`,
    ]),
    `});`,
    ``,
    `export { expect } from '@playwright/test';`,
    ``,
  ];
  return lines.join('\n');
}

/** LoginPage -> loginPage. */
function fixtureName(className: string): string {
  return className.charAt(0).toLowerCase() + className.slice(1);
}

function uniqueName(base: string, used: Set<string>): string {
  let name = base;
  let n = 2;
  while (used.has(name)) name = `${base}${n++}`;
  used.add(name);
  return name;
}
