/**
 * Generate a GitHub Actions workflow that runs the crystallized specs on every
 * PR — deterministically, with NO AI in the loop (Hover's core thesis: AI
 * authors the spec once, CI just runs plain `playwright test`).
 *
 * The workflow spins the app up inside CI (the project's dev script) and tests
 * localhost, so it's self-contained — no deployment pipeline required. Test
 * account credentials come from GitHub secrets using the same
 * `HOVER_<LABEL>_USER/PASS` names the Environments view exports, so authoring
 * (the vault) and CI (secrets) line up on one convention.
 *
 * A commented hook marks where Hover Cloud will later add on-failure self-heal
 * of drifted specs + a dashboard; until then a red check is a real regression.
 */

export interface CiWorkflowOptions {
  /** pnpm | yarn | bun | npm */
  packageManager: string;
  /** package.json script that starts the dev server (dev / start / serve). */
  devScript: string;
  /** URL the app serves on locally, e.g. http://localhost:5173. */
  appUrl: string;
  /** Account env-var names to wire as GitHub secrets (HOVER_<LABEL>_USER/PASS). */
  secretNames: string[];
}

interface PmConfig {
  setup: string[];
  cache: string;
  install: string;
  exec: string;
}

function pmConfig(pm: string): PmConfig {
  switch (pm) {
    case 'pnpm':
      return { setup: ['      - uses: pnpm/action-setup@v4'], cache: 'pnpm', install: 'pnpm install --frozen-lockfile', exec: 'pnpm exec' };
    case 'yarn':
      return { setup: [], cache: 'yarn', install: 'yarn install --frozen-lockfile', exec: 'yarn' };
    case 'bun':
      return { setup: ['      - uses: oven-sh/setup-bun@v2'], cache: '', install: 'bun install', exec: 'bunx' };
    default:
      return { setup: [], cache: 'npm', install: 'npm ci', exec: 'npx' };
  }
}

export function buildWorkflowYaml(o: CiWorkflowOptions): string {
  const pm = pmConfig(o.packageManager);
  const setupBlock = pm.setup.length ? pm.setup.join('\n') + '\n' : '';
  const cacheLine = pm.cache ? `\n          cache: ${pm.cache}` : '';
  const secretEnv = o.secretNames.length
    ? o.secretNames.map((n) => `          ${n}: \${{ secrets.${n} }}`).join('\n')
    : '          # No test-account secrets yet — add accounts in the Hover Environments view.';

  return `# Generated by Hover. Runs your crystallized Playwright specs on every PR —
# no AI in the loop, just deterministic tests. A red check = a real regression.
name: Hover E2E
on:
  pull_request:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${o.appUrl}
    steps:
      - uses: actions/checkout@v4
${setupBlock}      - uses: actions/setup-node@v4
        with:
          node-version: 20${cacheLine}
      - run: ${pm.install}
      - run: ${pm.exec} playwright install --with-deps chromium
      - name: Start the app
        run: ${o.packageManager} run ${o.devScript} &
      - name: Wait for the app
        run: npx --yes wait-on "$BASE_URL" --timeout 120000
      - name: Run Hover specs
        run: ${pm.exec} playwright test __vibe_tests__
        env:
${secretEnv}
      - uses: actions/upload-artifact@v4
        if: \${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
      # Hover Cloud (coming soon): on failure, auto-heal UI-drifted specs and
      # report to a dashboard. Until then, a red check is a genuine regression.
#
# Testing a deployed URL instead of building in CI? Delete the "Start the app"
# + "Wait for the app" steps and point BASE_URL at your deployment — or use a
# per-environment GitHub Environment secret for staging / prod.
`;
}
