/**
 * Generate a GitHub Actions workflow that runs the crystallized specs on every
 * PR — deterministically, with NO AI in the loop (Hover's core thesis: AI
 * authors the spec once, CI just runs plain `playwright test`).
 *
 * The workflow spins the app up inside CI (the project's dev script) and tests
 * localhost, so it's self-contained — no deployment pipeline required. Test
 * account credentials come from GitHub secrets using the same
 * `HOVER_<LABEL>_USER/PASS` names the Environments view exports, so authoring
 * (the vault) and CI (secrets) line up on one convention.
 *
 * It also writes a JSON report (`hover-results.json`) and uploads it as the
 * `hover-results` artifact — the structured result the Hover extension fetches
 * (via GitHub) to surface CI failures in the editor and offer 🏥 Heal on drifted
 * specs, with the heal running locally. No AI in CI; a red check is a real
 * regression until you heal it.
 *
 * Self-heal mode B1 (this file): on a red PR run, a `Report drifted specs` step
 * runs `.github/hover/drift-report.mjs` (DRIFT_REPORT_SCRIPT, written alongside
 * the workflow) to comment the drifted specs + a paste-ready `/mcp__hover__heal
 * <slug>` per spec on the PR — surfacing the heal task the moment it's red. Still
 * NO AI in CI: the heal itself runs locally. (Mode B2 — an opt-in job that heals
 * in CI with the user's own Claude + opens a PR — is a separate workflow.)
 */
import DRIFT_REPORT_SCRIPT from './assets/drift-report.mjs.txt';

/** The CI drift-dispatch script, written to `.github/hover/drift-report.mjs`. */
export { DRIFT_REPORT_SCRIPT };

export interface CiWorkflowOptions {
  /** pnpm | yarn | bun | npm */
  packageManager: string;
  /** package.json script that starts the dev server (dev / start / serve). */
  devScript: string;
  /** URL the app serves on locally, e.g. http://localhost:5173. */
  appUrl: string;
  /** Account env-var names to wire as GitHub secrets (HOVER_<LABEL>_USER/PASS). */
  secretNames: string[];
}

interface PmConfig {
  setup: string[];
  cache: string;
  install: string;
  exec: string;
}

function pmConfig(pm: string): PmConfig {
  switch (pm) {
    case 'pnpm':
      return { setup: ['      - uses: pnpm/action-setup@v4'], cache: 'pnpm', install: 'pnpm install --frozen-lockfile', exec: 'pnpm exec' };
    case 'yarn':
      return { setup: [], cache: 'yarn', install: 'yarn install --frozen-lockfile', exec: 'yarn' };
    case 'bun':
      return { setup: ['      - uses: oven-sh/setup-bun@v2'], cache: '', install: 'bun install', exec: 'bunx' };
    default:
      return { setup: [], cache: 'npm', install: 'npm ci', exec: 'npx' };
  }
}

export function buildWorkflowYaml(o: CiWorkflowOptions): string {
  const pm = pmConfig(o.packageManager);
  const setupBlock = pm.setup.length ? pm.setup.join('\n') + '\n' : '';
  const cacheLine = pm.cache ? `\n          cache: ${pm.cache}` : '';
  const secretEnv = o.secretNames.length
    ? o.secretNames.map((n) => `          ${n}: \${{ secrets.${n} }}`).join('\n')
    : '          # No test-account secrets yet — add accounts in the Hover Environments view.';

  return `# Generated by Hover. Runs your crystallized Playwright specs on every PR —
# no AI in the loop, just deterministic tests. A red check = a real regression.
name: Hover E2E
on:
  pull_request:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${o.appUrl}
    steps:
      - uses: actions/checkout@v4
${setupBlock}      - uses: actions/setup-node@v4
        with:
          node-version: 20${cacheLine}
      - run: ${pm.install}
      - run: ${pm.exec} playwright install --with-deps chromium
      - name: Start the app
        run: ${o.packageManager} run ${o.devScript} &
      - name: Wait for the app
        run: npx --yes wait-on "$BASE_URL" --timeout 120000
      - name: Run Hover specs
        run: ${pm.exec} playwright test __vibe_tests__ --reporter=html,json
        env:
          PLAYWRIGHT_JSON_OUTPUT_NAME: hover-results.json
${secretEnv}
      - name: Upload Hover results
        uses: actions/upload-artifact@v4
        if: \${{ !cancelled() }}
        with:
          name: hover-results
          path: hover-results.json
          retention-days: 14
      - uses: actions/upload-artifact@v4
        if: \${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
      # Self-heal B1: on a red PR run, comment the drifted specs + a paste-ready
      # /mcp__hover__heal command for each. The heal still runs LOCALLY (your
      # browser + your agent) — this just surfaces it on the PR, no AI in CI.
      - name: Report drifted specs (Hover self-heal)
        if: \${{ failure() && github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          node .github/hover/drift-report.mjs || exit 0
          if [ -f hover-drift.md ]; then
            gh pr comment "\${{ github.event.pull_request.number }}" --body-file hover-drift.md || true
          fi
      # The hover-results artifact (Playwright JSON) is what the Hover VS Code
      # extension reads to surface CI failures in the editor and offer 🏥 Heal on
      # drifted specs — the heal runs LOCALLY (your browser + your agent), no AI
      # in CI. Until you connect the extension, a red check is a real regression.
#
# Testing a deployed URL instead of building in CI? Delete the "Start the app"
# + "Wait for the app" steps and point BASE_URL at your deployment — or use a
# per-environment GitHub Environment secret for staging / prod.
`;
}
