import { test, expect } from '@playwright/test';

/**
 * Generated by Hover on 2026-06-05.
 * Original prompt: 只测试登录
 * Outcome: `wrong@test.com` + `pass1` 成功登录，确认 app 不校验真实凭证（此乃预期行为）。现在可以归纳结果了。
 *
 * Steps:
 *   1. Fill email="alice@example.com", password="password"
 *   2. Click Submit button
 *   3. Click Log out button
 *   4. Click Submit button
 *   5. Fill email="alice@example.com"
 *   6. Click Submit button
 *   7. Fill email="notanemail", password="password"
 *   8. Click Submit button
 *   9. Fill email="notanemail", password="pass"
 *   10. Click Submit button
 *   11. Fill password="pass1"
 *   12. Click Submit button
 *   13. Fill email="wrong@test.com", password="pass1"
 *   14. Click Submit button
 *
 * Expected:
 *   • `wrong@test.com` + `pass1` 成功登录，确认 app 不校验真实凭证（此乃预期行为）。现在可以归纳结果了。

---

## 登录流程测试结果

**执行的测试步骤：**

1.
 *
 * Selectors prefer getByRole / getByLabel / getByTestId — generated from
 * the agent's natural-language element descriptions, not raw CSS ids,
 * so the spec survives markup changes that don't touch semantics.
 */
test('login-flow', async ({ page }) => {
  await test.step("When · Skill", async () => {
    // TODO: translate Skill (skipped — unknown tool for spec emission)
  });
  await test.step("When · Fill email=\"alice@example.com\", password=\"password\"", async () => {
    {
      const el = page.getByRole('textbox', { name: "email" });
      await expect(el).toBeVisible();
      await el.fill("alice@example.com");
    }
    {
      const el = page.getByRole('textbox', { name: "password" });
      await expect(el).toBeVisible();
      await el.fill("password");
    }
  });
  await test.step("When · Click Submit button", async () => {
    const el = page.getByRole('button', { name: "Submit" });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click Log out button", async () => {
    const el = page.getByRole('button', { name: "Log out" });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Click Submit button", async () => {
    const el = page.getByRole('button', { name: "Submit" });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Fill email=\"alice@example.com\"", async () => {
    {
      const el = page.getByRole('textbox', { name: "email" });
      await expect(el).toBeVisible();
      await el.fill("alice@example.com");
    }
  });
  await test.step("When · Click Submit button", async () => {
    const el = page.getByRole('button', { name: "Submit" });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Fill email=\"notanemail\", password=\"password\"", async () => {
    {
      const el = page.getByRole('textbox', { name: "email" });
      await expect(el).toBeVisible();
      await el.fill("notanemail");
    }
    {
      const el = page.getByRole('textbox', { name: "password" });
      await expect(el).toBeVisible();
      await el.fill("password");
    }
  });
  await test.step("When · Click Submit button", async () => {
    const el = page.getByRole('button', { name: "Submit" });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Fill email=\"notanemail\", password=\"pass\"", async () => {
    {
      const el = page.getByRole('textbox', { name: "email" });
      await expect(el).toBeVisible();
      await el.fill("notanemail");
    }
    {
      const el = page.getByRole('textbox', { name: "password" });
      await expect(el).toBeVisible();
      await el.fill("pass");
    }
  });
  await test.step("When · Click Submit button", async () => {
    const el = page.getByRole('button', { name: "Submit" });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Fill password=\"pass1\"", async () => {
    {
      const el = page.getByRole('textbox', { name: "password" });
      await expect(el).toBeVisible();
      await el.fill("pass1");
    }
  });
  await test.step("When · Click Submit button", async () => {
    const el = page.getByRole('button', { name: "Submit" });
    await expect(el).toBeVisible();
    await el.click();
  });
  await test.step("When · Fill email=\"wrong@test.com\", password=\"pass1\"", async () => {
    {
      const el = page.getByRole('textbox', { name: "email" });
      await expect(el).toBeVisible();
      await el.fill("wrong@test.com");
    }
    {
      const el = page.getByRole('textbox', { name: "password" });
      await expect(el).toBeVisible();
      await el.fill("pass1");
    }
  });
  await test.step("When · Click Submit button", async () => {
    const el = page.getByRole('button', { name: "Submit" });
    await expect(el).toBeVisible();
    await el.click();
  });
});
