'use client';

import { useEffect, useRef, useState } from 'react';

/**
 * The explore → crystallise story as a self-typing terminal panel, styled like
 * the widget's dark inset code blocks. The prompt types in, the left-rail steps
 * light up, and the spec on the right reveals line by line — as if Hover were
 * generating it live — then it loops to the next scene.
 *
 * Each scene's spec is the REAL deterministic output of writeSpec.ts: a JSDoc
 * header (Generated / Original prompt / numbered Steps / Expected) followed by
 * getByLabel / getByRole semantic selectors, every interaction wrapped in a
 * block-scoped visibility guard, quote styles matching the emitter
 * (JSON.stringify values), goto stripped to a relative path. No getByPlaceholder
 * (the translator has no such path), no idealised one-liners — what types out is
 * what lands in __vibe_tests__/. (The one header line we omit is the fixed
 * "Selectors prefer …" note, which still advertises getByTestId the emitter
 * doesn't produce — tracked for the README/code fix, kept out of the demo.)
 *
 * SSR-safe: initial state shows the first scene in full, so crawlers and
 * reduced-motion / no-JS visitors read a complete spec. The mount effect rewinds
 * to the animated start only when motion is allowed.
 */

type Scene = {
  file: string;
  prompt: string;
  /** `at` = the spec-line count at which the step flips to done. */
  steps: { label: string; at: number }[];
  spec: string[];
};

const SCENES: Scene[] = [
  {
    file: '__vibe_tests__/login-flow.spec.ts',
    prompt: 'log in, then add a todo named "verify hover"',
    steps: [
      { label: 'Opening page', at: 17 },
      { label: 'Filling login form', at: 23 },
      { label: 'Clicking Sign in', at: 29 },
      { label: 'Typing todo', at: 34 },
      { label: 'Done · 11 steps · $0.16', at: 35 },
    ],
    spec: [
      `/**`,
      ` * Generated by Hover on 2026-06-01.`,
      ` * Original prompt: log in, then add a todo named "verify hover"`,
      ` *`,
      ` * Steps:`,
      ` *   1. Open http://localhost:5173/`,
      ` *   2. Fill Email="claude@…"`,
      ` *   3. Click Sign in button`,
      ` *   4. Fill New todo="verify hover"`,
      ` *`,
      ` * Expected:`,
      ` *   • "verify hover" is visible`,
      ` */`,
      `import { test, expect } from '@playwright/test';`,
      ``,
      `test('login then add todo', async ({ page }) => {`,
      `  await page.goto("/");`,
      ``,
      `  {`,
      `    const el = page.getByLabel("Email");`,
      `    await expect(el).toBeVisible();`,
      `    await el.fill("claude@…");`,
      `  }`,
      `  {`,
      `    const el = page.getByRole('button',`,
      `      { name: "Sign in" });`,
      `    await expect(el).toBeVisible();`,
      `    await el.click();`,
      `  }`,
      `  {`,
      `    const el = page.getByLabel("New todo");`,
      `    await expect(el).toBeVisible();`,
      `    await el.fill("verify hover");`,
      `  }`,
      `});`,
    ],
  },
  {
    file: '__vibe_tests__/add-to-cart.spec.ts',
    prompt: 'add the top-rated headphones to my cart',
    steps: [
      { label: 'Opening store', at: 16 },
      { label: 'Opening product', at: 23 },
      { label: 'Adding to cart', at: 28 },
      { label: 'Verifying cart', at: 29 },
      { label: 'Done · 9 steps · $0.12', at: 30 },
    ],
    spec: [
      `/**`,
      ` * Generated by Hover on 2026-06-01.`,
      ` * Original prompt: add the top-rated headphones to my cart`,
      ` *`,
      ` * Steps:`,
      ` *   1. Open http://localhost:5174/`,
      ` *   2. Click Studio Headphones link`,
      ` *   3. Click Add to cart button`,
      ` *`,
      ` * Expected:`,
      ` *   • "1 item in cart" is visible`,
      ` */`,
      `import { test, expect } from '@playwright/test';`,
      ``,
      `test('add headphones to cart', async ({ page }) => {`,
      `  await page.goto("/");`,
      ``,
      `  {`,
      `    const el = page.getByRole('link',`,
      `      { name: "Studio Headphones" });`,
      `    await expect(el).toBeVisible();`,
      `    await el.click();`,
      `  }`,
      `  {`,
      `    const el = page.getByRole('button', { name: "Add to cart" });`,
      `    await expect(el).toBeVisible();`,
      `    await el.click();`,
      `  }`,
      `  await expect(page.getByText("1 item in cart")).toBeVisible();`,
      `});`,
    ],
  },
  {
    file: '__vibe_tests__/shipping-address.spec.ts',
    prompt: 'fill in my shipping address',
    steps: [
      { label: 'Opening checkout', at: 17 },
      { label: 'Filling name', at: 23 },
      { label: 'Filling address', at: 28 },
      { label: 'Filling city', at: 33 },
      { label: 'Done · 7 steps · $0.09', at: 34 },
    ],
    spec: [
      `/**`,
      ` * Generated by Hover on 2026-06-01.`,
      ` * Original prompt: fill in my shipping address`,
      ` *`,
      ` * Steps:`,
      ` *   1. Open http://localhost:5174/checkout`,
      ` *   2. Fill Full name="Ada Lovelace"`,
      ` *   3. Fill Address line 1="12 Analytical Ave"`,
      ` *   4. Fill City="London"`,
      ` *`,
      ` * Expected:`,
      ` *   • Shipping address saved`,
      ` */`,
      `import { test, expect } from '@playwright/test';`,
      ``,
      `test('fill shipping address', async ({ page }) => {`,
      `  await page.goto("/checkout");`,
      ``,
      `  {`,
      `    const el = page.getByLabel("Full name");`,
      `    await expect(el).toBeVisible();`,
      `    await el.fill("Ada Lovelace");`,
      `  }`,
      `  {`,
      `    const el = page.getByLabel("Address line 1");`,
      `    await expect(el).toBeVisible();`,
      `    await el.fill("12 Analytical Ave");`,
      `  }`,
      `  {`,
      `    const el = page.getByLabel("City");`,
      `    await expect(el).toBeVisible();`,
      `    await el.fill("London");`,
      `  }`,
      `});`,
    ],
  },
];

type Phase = 'static' | 'typing' | 'building' | 'hold';

export function TerminalDemo() {
  const [sceneIdx, setSceneIdx] = useState(0);
  const [phase, setPhase] = useState<Phase>('static');
  const [typed, setTyped] = useState(SCENES[0].prompt);
  const [lines, setLines] = useState(SCENES[0].spec.length);

  const scene = SCENES[sceneIdx];
  const preRef = useRef<HTMLPreElement>(null);

  // On mount, rewind to the animated start unless the user prefers less motion.
  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    setTyped('');
    setLines(0);
    setPhase('typing');
  }, []);

  // Prompt typewriter.
  useEffect(() => {
    if (phase !== 'typing') return;
    const prompt = SCENES[sceneIdx].prompt;
    let i = 0;
    const id = setInterval(() => {
      i += 1;
      setTyped(prompt.slice(0, i));
      if (i >= prompt.length) {
        clearInterval(id);
        setPhase('building');
      }
    }, 32);
    return () => clearInterval(id);
  }, [phase, sceneIdx]);

  // Spec revealed one line at a time.
  useEffect(() => {
    if (phase !== 'building') return;
    const total = SCENES[sceneIdx].spec.length;
    let n = 0;
    const id = setInterval(() => {
      n += 1;
      setLines(n);
      if (n >= total) {
        clearInterval(id);
        setPhase('hold');
      }
    }, 110);
    return () => clearInterval(id);
  }, [phase, sceneIdx]);

  // Hold the finished frame, then advance to the next scene and loop.
  useEffect(() => {
    if (phase !== 'hold') return;
    const id = setTimeout(() => {
      setSceneIdx((s) => (s + 1) % SCENES.length);
      setTyped('');
      setLines(0);
      setPhase('typing');
    }, 3000);
    return () => clearTimeout(id);
  }, [phase]);

  // Follow the freshly-typed line while building. On hold, let the finished
  // frame rest at the bottom for a beat, then ease (not jump) back to the top so
  // the held frame reads from the JSDoc header down. typing/static reset flat.
  useEffect(() => {
    const el = preRef.current;
    if (!el) return;
    if (phase === 'building') {
      el.scrollTop = el.scrollHeight;
      return;
    }
    if (phase !== 'hold') {
      el.scrollTop = 0;
      return;
    }
    const id = setTimeout(() => {
      preRef.current?.scrollTo({ top: 0, behavior: 'smooth' });
    }, 900);
    return () => clearTimeout(id);
  }, [phase, lines]);

  const stepStateFor = (at: number, prevAt: number): 'pending' | 'running' | 'done' => {
    if (phase === 'static' || phase === 'hold') return 'done';
    if (lines >= at) return 'done';
    if (lines >= prevAt) return 'running';
    return 'pending';
  };

  return (
    <div className="mt-16 overflow-hidden rounded-lg border border-line bg-bg-3 shadow-[0_18px_48px_rgba(0,0,0,0.55)]">
      <div className="flex items-center gap-2 border-b border-line bg-bg-2 px-4 py-2.5">
        <span className="h-3 w-3 rounded-full bg-line-2" />
        <span className="h-3 w-3 rounded-full bg-line-2" />
        <span className="h-3 w-3 rounded-full bg-line-2" />
        <span className="ml-2 font-mono text-[12px] text-text-dim">hover · examples</span>
        {/* Scene dots — which of the looping flows is on screen. */}
        <span className="ml-auto flex items-center gap-1.5">
          {SCENES.map((s, i) => (
            <span
              key={s.file}
              className={`h-1.5 w-1.5 rounded-full transition-colors ${i === sceneIdx ? 'bg-mint' : 'bg-line-2'}`}
            />
          ))}
        </span>
      </div>
      <div className="grid gap-px bg-line md:grid-cols-2">
        {/* Left — you type */}
        <div className="min-w-0 bg-bg-3 p-5">
          <div className="mb-3 font-mono text-[11px] uppercase tracking-wider text-text-dim">
            You type
          </div>
          <p className="min-h-[3em] font-mono text-[14px] leading-relaxed text-text">
            <span className="text-mint">› </span>
            {typed}
            {phase === 'typing' && <Caret />}
          </p>
          <div className="mt-5 space-y-2 font-mono text-[13px] text-text-mute">
            {scene.steps.map((s, i) => (
              <StepRow
                key={s.label}
                label={s.label}
                state={stepStateFor(s.at, i === 0 ? 0 : scene.steps[i - 1].at)}
                last={i === scene.steps.length - 1}
              />
            ))}
          </div>
        </div>
        {/* Right — Hover saves */}
        <div className="min-w-0 bg-bg-3 p-5">
          <div className="mb-3 break-all font-mono text-[11px] uppercase tracking-wider text-text-dim">
            Hover saves <span className="text-mint">{scene.file}</span>
          </div>
          <pre ref={preRef} className="td-pre h-108 overflow-auto font-mono text-[12.5px] leading-relaxed text-text-mute">
            <code>
              {scene.spec.slice(0, lines).join('\n')}
              {phase === 'building' && <Caret />}
            </code>
          </pre>
          <div className="mt-3 font-mono text-[11px] text-text-dim">
            runs with <span className="text-text-mute">npx playwright test</span> — no agent, no key
          </div>
        </div>
      </div>

      <style>{`
        @keyframes td-blink { 0%,49% { opacity: 1 } 50%,100% { opacity: 0 } }
        /* Scrollbar matched to the real widget (style.css): thin, dark thumb,
           transparent track — so a long selector line scrolls quietly instead
           of showing the OS default bar. */
        .td-pre { scrollbar-width: thin; scrollbar-color: #2a2a2c transparent; }
        .td-pre::-webkit-scrollbar { width: 8px; height: 8px; }
        .td-pre::-webkit-scrollbar-track { background: transparent; }
        .td-pre::-webkit-scrollbar-thumb {
          background: #2a2a2c; border-radius: 999px;
          border: 2px solid transparent; background-clip: padding-box;
        }
        .td-pre::-webkit-scrollbar-thumb:hover { background: #3a3a3c; background-clip: padding-box; }
      `}</style>
    </div>
  );
}

function Caret() {
  return (
    <span
      aria-hidden
      className="ml-0.5 inline-block h-[1.05em] w-0.5 translate-y-0.5 bg-mint align-middle"
      style={{ animation: 'td-blink 0.9s steps(2) infinite' }}
    />
  );
}

function StepRow({
  label,
  state,
  last,
}: {
  label: string;
  state: 'pending' | 'running' | 'done';
  last?: boolean;
}) {
  const dot = state === 'pending' ? 'bg-line-2' : 'bg-mint';
  const text =
    state === 'pending' ? undefined : last ? 'text-mint' : state === 'running' ? 'text-text' : undefined;
  return (
    <div
      className="flex items-center gap-2.5 transition-opacity duration-300"
      style={{ opacity: state === 'pending' ? 0.3 : 1 }}
    >
      <span className={`h-1.5 w-1.5 rounded-full ${dot}`} />
      <span className={text}>{label}</span>
    </div>
  );
}
